id: I9B5CF76E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:12:16+00:00'
last_modified: '2022-06-07T12:38:08.198565+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15995
  title: རིགས་ལམ་སྦྱོང་སྟངས་དང་སྦྱར་བའི་དངོས་གཞིའི་སློབ་དེབ་རིག་པའི་ཉིན་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BE4E:
      image_group_id: I1KG16201
      title: ''
      total_pages: 140
      order: 1
      base_file: BE4E.txt
    7C19:
      image_group_id: I1KG16202
      title: ''
      total_pages: 106
      order: 2
      base_file: 7C19.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
