id: I9B5CF76E
legacy_id: P000675
ocr_import_info:
  bdrc_scan_id: W1KG15995
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T13:11:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:38:06.832576+00:00'
last_modified: 2022-08-27 13:38:30.372286
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15995
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15995
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རིགས་ལམ་སྦྱོང་སྟངས་དང་སྦྱར་བའི་དངོས་གཞིའི་སློབ་དེབ་རིག་པའི་ཉིན་བྱེད།
statistics:
  ocr_word_mean_confidence_index: 0.9689075506475338
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG16202:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16202
      total_pages: 106
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG16202.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9692447914102045
    legacy_id: v002
  I1KG16201:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16201
      total_pages: 140
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16201.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9686536540212627
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
